import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        "primary-fixed": "#a7f78a",
        "on-secondary-container": "#725f00",
        tertiary: "#ffb4a8",
        "surface-container-low": "#1b1b1c",
        "surface-variant": "#353535",
        background: "#131313",
        "tertiary-container": "#ec0000",
        "on-tertiary": "#690100",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#202020",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-tertiary-container": "#fffdff",
        "tertiary-fixed-dim": "#ffb4a8",
        "secondary-fixed": "#ffe16d",
        outline: "#8a9483",
        "on-secondary-fixed-variant": "#544600",
        "tertiary-fixed": "#ffdad4",
        "on-secondary": "#3a3000",
        "on-error-container": "#ffdad6",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#105300",
        "inverse-on-surface": "#303030",
        "on-tertiary-fixed": "#410000",
        "surface-container-highest": "#353535",
        "secondary-fixed-dim": "#e9c400",
        "on-primary": "#093900",
        "on-secondary-fixed": "#221b00",
        "surface-container-lowest": "#0e0e0e",
        primary: "#8cda70",
        "surface-bright": "#393939",
        "surface-tint": "#8cda70",
        surface: "#131313",
        "on-primary-fixed": "#032100",
        "primary-container": "#3c8527",
        "on-tertiary-fixed-variant": "#930100",
        "on-surface-variant": "#c0cab7",
        "primary-fixed-dim": "#8cda70",
        "inverse-primary": "#236d0f",
        secondary: "#fff9ef",
        "secondary-container": "#ffdb3c",
        "on-primary-container": "#fdfff5",
        error: "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "outline-variant": "#41493b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        xs: "4px",
        lg: "48px",
        "margin-mobile": "16px",
        gutter: "24px",
        md: "24px",
        xl: "80px",
        "container-max": "1280px",
        base: "8px",
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["14px", { lineHeight: "1.0", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;